### ISSUE TITLE
[12.0] New addon - hide time information on timesheet report

### ISSUE THREAD

**Issue by dalonsod** [solvosci/slv-timesheet#1]
I've found that it could be useful enabling an extra PDF timesheet detiailed report without time information, because some customers shouldn't need that information.

Hiding that information, should give us an extra advantage: more width available for the other columns, like timesheet description.

The requirements should be the following:
- New server action, the same as the existing one, with " - not valued" text or something like that.
- The current report should remain unchanged.
- The new report will hide time information.

@lmiguens-solvos @ChristianSantamaria what do you think?

**Comment by ChristianSantamaria** [comment]
I have uploaded a PR with a new addon with this suggestion https://github.com/solvosci/slv-timesheet/pull/2

**Comment by dalonsod** [comment]
Closing this, since #2 is merged
